{
 "title": "http navigatorx",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Count 24H",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(navigatorx_total_requests[24h])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(navigatorx_total_requests[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Response Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "floor(sum(increase(navigatorx_total_requests{status=~'500'})))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(navigatorx_request_duration_seconds_bucket[1m])) by(le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(navigatorx_request_duration_seconds_bucket[1m]))  by(le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(navigatorx_request_duration_seconds_bucket[1m]))  by(le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(navigatorx_request_duration_seconds_bucket[1m])) by(le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(navigatorx_total_requests[1m])) by(path, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "navigatorx_response_status_code",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shortest Path Query Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "navigatorx_shortestpath_query_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(navigatorx_total_requests{status=\"500\"}[1m])) / sum(rate(navigatorx_total_requests{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}