package guidance

const (
	RELATIVE_BEARING_U_TURN float64 = 100.0
	MERGE_RELATIVE_BEARING  float64 = 40.0

	KEEP_LEFT_RIGHT_ALT_TURN_RELATIVE_BEARING float64 = 20.0
	CONTINUE_ALT_TURN_RELATIVE_BEARING        float64 = 8.6
	CONTINUE_ALT_CURRENT_RELATIVE_BEARING     float64 = 7
	U_TURN_RELATIVE_BEARING_MIN               float64 = 160
	U_TURN_RELATIVE_BEARING_MAX               float64 = 185
)
