package guidance

const (
	DELTA_BEARING_U_TURN float64 = 100.0
	MERGE_DELTA_BEARING  float64 = 40.0

	KEEP_LEFT_RIGHT_ALT_TURN_DELTA_BEARING float64 = 20.0
	CONTINUE_ALT_TURN_DELTA_BEARING        float64 = 8.6
	CONTINUE_ALT_CURRENT_DELTA_BEARING         float64 = 7
)
