repos:
- repo: local
  hooks:
    - id: sync-software-version
      name: sync software version from latest git tag
      entry: scripts/sync_software_version.sh
      language: system
      pass_filenames: false
      always_run: true

- repo: https://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
      args: ["-w", "-s"]
    - id: go-imports
    - id: golangci-lint
      args: ["-c=conf/.golangci.yml"]
    - id: go-mod-tidy
