version: "3"
services:
  navigatorx:
    container_name: navigatorx
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAP_FILE: solo_jogja
        DRIVE_FILE_ID: 1pEHN8wwUbB5XpuYMZm141fXQ_ZsIf4CO
    mem_limit: 2000mb
    cpus: 6
    ports:
      - "5000:5000"
  prometheus:
    image: prom/prometheus:v2.40.0
    volumes:
      - ./deploy/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
    depends_on:
      - cadvisor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.4"
    #       memory: 300mb
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    labels:
      - prometheus-job=cadvisor
    privileged: true





 #for logging
  # elasticsearch:
  #       image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
  #       volumes:
  #           - ./deploy/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  #       healthcheck:
  #           test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
  #           interval: 3s
  #           timeout: 3s
  #           retries: 10
  #       ports:
  #           - 9200:9200

  # logstash:
  #     image: docker.elastic.co/logstash/logstash:7.6.2
  #     volumes:
  #         - ./deploy/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
  #     depends_on:
  #         elasticsearch:
  #             condition: service_healthy

  # filebeat:
  #     image: docker.elastic.co/beats/filebeat:6.5.1
  #     depends_on:
  #         elasticsearch:
  #             condition: service_healthy
  #     volumes:
  #         - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #         - ./logs/:/logs/

  # kibana:
  #     image: docker.elastic.co/kibana/kibana:7.6.2
  #     depends_on:
  #         elasticsearch:
  #             condition: service_healthy
  #     healthcheck:
  #         test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
  #         interval: 3s
  #         timeout: 3s
  #         retries: 50
  #     ports:
  #         - 5601:5601


volumes:
  grafana-storage:
  prometheus_data: