version: "3"
services:
  navigatorx:
    container_name: navigatorx
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAP_FILE: solo_jogja
        DRIVE_FILE_ID: 1pEHN8wwUbB5XpuYMZm141fXQ_ZsIf4CO
    mem_limit: 2000mb
    cpus: 6
    ports:
      - "5000:5000"