package routing

const (
	UNPACK_OVERLAY_OFFSET          int  = 31 // set 32-th bit on
	PATH_UNPACKER_WORKERS          int  = 3
	ALTERNATIVE_ROUTES_WORKERS          = 4
	USE_CRP_FOR_ALTERNATIVE_ROUTES bool = true

	MAX_FILTERED_ALTERNATIVE_ROUTE_CANDIDATES = 10
)
