#!/bin/bash
# Generated by Gemini 3 flash 

# https://go.dev/doc/pgo

# Exit on error
set -e

# Determine the root directory of the project
ROOT_DIR=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
BENCH_DIR="$ROOT_DIR/tests/benchmark"
ENGINE_CMD_DIR="$ROOT_DIR/bin"
PGO_OUTPUT="$ENGINE_CMD_DIR/default.pgo"

# Ensure the bin directory exists with 755 permissions
if [ ! -d "$ENGINE_CMD_DIR" ]; then
    echo "Creating directory $ENGINE_CMD_DIR with 755 permissions..."
    mkdir -m 755 -p "$ENGINE_CMD_DIR"
fi

echo "Starting PGO profile collection..."

# Move to benchmark directory to ensure data paths (./data) are correct for benchmarks
cd "$BENCH_DIR"

# 1. Run benchmarks and collect profiles
# We use unique filenames to avoid overwriting results
echo "⏱️ Running BenchmarkAlternativeRoutes..."
go test -bench ^BenchmarkAlternativeRoutes$ -benchmem -cpuprofile prof_alt.cpu -memprofile prof_alt.mem -benchtime=15s

echo "⏱️ Running BenchmarkAlternativeRoutesController..."
go test -bench ^BenchmarkAlternativeRoutesController$ -benchmem -cpuprofile prof_alt_controller.cpu -memprofile prof_alt_controller.mem -benchtime=15s

echo "⏱️ Running BenchmarkAlternativeRoutesService..."
go test -bench ^BenchmarkAlternativeRoutesService$ -benchmem -cpuprofile prof_alt_service.cpu -memprofile prof_alt_service.mem -benchtime=15s

echo "⏱️ Running BenchmarkShortestPathService..."
go test -bench ^BenchmarkShortestPathService$ -benchmem -cpuprofile prof_sp_service.cpu -memprofile prof_sp_service.mem -benchtime=15s

echo "⏱️ Running BenchmarkCRPALTQuery..."
go test -bench ^BenchmarkCRPALTQuery$ -benchmem -cpuprofile prof.cpu -memprofile prof.mem -benchtime=15s

# 2. Merge all CPU profiles into a single PGO file
echo "Merging profiles into $PGO_OUTPUT..."
go tool pprof -proto \
    prof_alt.cpu \
    prof_alt_controller.cpu \
    prof_alt_service.cpu \
    prof_sp_service.cpu \
    prof.cpu \
    > "$PGO_OUTPUT"

# 3. Cleanup temporary files
echo "Cleaning up temporary profile files..."
rm -f *.cpu *.mem

echo "PGO profile generated successfully at $PGO_OUTPUT"




