name: test
on:
  push:
  pull_request:
permissions:
  contents: write
  pull-requests: write
jobs:
  check-coverage:
    name: Go test coverage check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.26.1' 

      - name: generate test coverage
        run: sh ./scripts/run_test.sh

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.github/.testcoverage.yml
